//! The LCD's host text slot: what goes on the two lines, and the bytes for it.
//!
//! Port of `hostagent/ak820text.py`. That file remains the oracle — it drives
//! the macOS agent too — so the rule here is **produce the same bytes**, not
//! "produce reasonable bytes". Where its behaviour looks odd, it is reproduced
//! and the oddity documented rather than improved; a port that quietly renders
//! track titles differently is a port that will be blamed for a firmware bug.
//!
//! The wire, all on `Channel::Text`:
//!
//! ```text
//! [SET]      icon, ascii...          legacy one-liner; line 0's budget
//! [CLEAR]                            hand the band back to the clock
//! [SET_LINE] line, icon, ascii...    the two-line form the agents use
//! [PLAYBACK] state, pos_hi, pos_lo, dur_hi, dur_lo
//! ```
//!
//! This module builds **bodies**, not whole reports: [`crate::proto::frame`]
//! owns the framing and the zero padding, so there is one place where a report
//! is laid out and one place to get it wrong.

mod fold_table;

pub use fold_table::PY_SPACE;

/// Commands on the text channel, matching `hid_protocol.c`.
pub const SET: u8 = 0x01;
pub const CLEAR: u8 = 0x02;
pub const SET_LINE: u8 = 0x03;
pub const PLAYBACK: u8 = 0x04;

/// Characters that survive on each line, indexed by line number.
///
/// Matches `DISPLAY_TEXT_MAX_L0`/`L1` in the firmware, which clamps too — this
/// is here so the producer knows what will actually be seen. Line 0 shares its
/// row with the transport icon and loses the 14 px gutter: `(128 - 14) / 6 = 19`.
/// Line 1 runs full width: `(128 - 2) / 6 = 21`.
pub const MAX_LEN: [usize; 2] = [19, 21];

/// Which of the two rows, and therefore which budget.
///
/// Named for the physical property that sets the budget rather than for what
/// the now-playing agent happens to put there. The producer decides content;
/// this layer only knows one row is narrower because an icon shares it.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum Line {
    /// Row 0 — 19 characters, beside the transport icon.
    WithIcon = 0,
    /// Row 1 — 21 characters, the full width of the panel.
    FullWidth = 1,
}

impl Line {
    pub fn index(self) -> u8 {
        self as u8
    }

    pub fn budget(self) -> usize {
        MAX_LEN[self as usize]
    }
}

/// The transport glyph drawn beside line 0.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Default)]
#[repr(u8)]
pub enum Icon {
    #[default]
    None = 0,
    Play = 1,
    Pause = 2,
    Stop = 3,
}

impl Icon {
    pub fn id(self) -> u8 {
        self as u8
    }
}

/// Fold one non-ASCII character to the ASCII it contributes, if any.
///
/// `None` means it contributes nothing, which is what
/// `.encode("ascii", "ignore")` does to it in Python.
fn fold(c: char) -> Option<&'static str> {
    let key = c as u32;
    let i = fold_table::KEYS.binary_search(&key).ok()?;
    let (from, to) = (
        fold_table::OFFSETS[i] as usize,
        fold_table::OFFSETS[i + 1] as usize,
    );
    Some(&fold_table::BLOB[from..to])
}

/// Reduce arbitrary text to the printable ASCII the font atlases carry.
///
/// Reproduces `ak820text.to_ascii` exactly — see
/// `tests/ascii_fold_parity.rs`, whose expected values are generated by
/// calling that Python function itself.
///
/// Three behaviours worth knowing, because each looks like a bug until you see
/// why:
///
/// - **Accents are stripped, not replaced.** `Beyoncé` becomes `Beyonce`. The
///   atlases hold printable ASCII only, and a dropped accent reads better than
///   the `?` the firmware would otherwise substitute.
/// - **Curly quotes and dashes are transliterated, not decomposed.** `U+2018`
///   and `U+2013` have no compatibility decomposition, so without the explicit
///   substitution they would vanish entirely rather than become `'` and `-`.
/// - **Control characters become `?`, and only control characters do.** They
///   are ASCII, so they survive the drop step; the `?` is what makes a stray
///   tab visible instead of silently shifting the layout.
pub fn to_ascii(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c as u32 {
            // Printable ASCII passes through untouched.
            0x20..=0x7E => out.push(c),
            // The rest of ASCII is C0 controls and DEL.
            0x00..=0x7F => out.push('?'),
            _ => {
                if let Some(folded) = fold(c) {
                    out.push_str(folded);
                }
            }
        }
    }
    out
}

/// Fold, then cut to `budget` characters.
///
/// ⚠️ Order matters and is not obvious. Python truncates the **folded** string,
/// so an ellipsis that expands to `...` spends three characters of the budget,
/// and an accented name spends the same as its unaccented form. Truncating
/// first would fit more text on some inputs and produce different bytes on
/// many — which is exactly the kind of divergence nobody would notice until a
/// title looked subtly wrong.
///
/// The result is ASCII, so a byte cut is a character cut and cannot split a
/// code point.
pub fn fit(text: &str, budget: usize) -> String {
    let mut folded = to_ascii(text);
    folded.truncate(budget);
    folded
}

/// Body of a `SET_LINE`: `[line, icon, ascii...]`.
pub fn line_body(line: Line, text: &str, icon: Icon) -> Vec<u8> {
    let mut body = vec![line.index(), icon.id()];
    body.extend_from_slice(fit(text, line.budget()).as_bytes());
    body
}

/// Body of the legacy single-line `SET`: `[icon, ascii...]`.
///
/// The firmware treats `SET` as line 0, so it carries line 0's budget. Kept
/// because `ak820text.py` still sends it and the firmware still accepts it;
/// the agents use [`line_body`].
pub fn set_body(text: &str, icon: Icon) -> Vec<u8> {
    let mut body = vec![icon.id()];
    body.extend_from_slice(fit(text, MAX_LEN[0]).as_bytes());
    body
}

/// Body of a `PLAYBACK`: `[state, pos_hi, pos_lo, dur_hi, dur_lo]`.
///
/// Seconds, **big-endian** — unlike every other multi-byte field in this
/// protocol, which is little-endian. 16 bits reaches 18.2 hours, past any
/// track. `state = 0` hands the band back to the clock.
///
/// Saturating rather than wrapping: a duration past 18 hours is a broken
/// timeline, and clamping shows a stuck bar while wrapping would show a
/// plausible wrong one.
pub fn playback_body(playing: bool, pos_s: u32, dur_s: u32) -> [u8; 5] {
    let pos = pos_s.min(u16::MAX as u32) as u16;
    let dur = dur_s.min(u16::MAX as u32) as u16;
    [
        playing as u8,
        (pos >> 8) as u8,
        pos as u8,
        (dur >> 8) as u8,
        dur as u8,
    ]
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::proto::{self, Channel};

    #[test]
    fn printable_ascii_is_untouched() {
        let s = " !\"#$%&'()*+,-./0123456789:;<=>?@AZ[\\]^_`az{|}~";
        assert_eq!(to_ascii(s), s);
    }

    #[test]
    fn accents_lose_their_marks() {
        assert_eq!(to_ascii("Beyoncé"), "Beyonce");
        assert_eq!(to_ascii("Sigur Rós"), "Sigur Ros");
        assert_eq!(to_ascii("Motörhead"), "Motorhead");
        // Already-decomposed input: the base letter survives, the mark does not.
        assert_eq!(to_ascii("e\u{301}galite\u{301}"), "egalite");
    }

    /// These have no decomposition at all, so without the explicit
    /// substitution they would vanish rather than transliterate.
    #[test]
    fn smart_punctuation_transliterates_rather_than_vanishing() {
        assert_eq!(to_ascii("\u{2018}Heroes\u{2019}"), "'Heroes'");
        assert_eq!(to_ascii("\u{201C}Quoted\u{201D}"), "\"Quoted\"");
        assert_eq!(to_ascii("A\u{2013}B"), "A-B");
        assert_eq!(to_ascii("A\u{2014}B"), "A-B");
        assert_eq!(to_ascii("wait\u{2026}"), "wait...");
        assert_eq!(to_ascii("a\u{A0}b"), "a b");
    }

    #[test]
    fn scripts_with_no_ascii_are_dropped_entirely() {
        assert_eq!(to_ascii("中文"), "");
        assert_eq!(to_ascii("Ж"), "");
        assert_eq!(to_ascii("🎵"), "");
        assert_eq!(to_ascii("あ"), "");
        assert_eq!(to_ascii("東京 Tokyo"), " Tokyo");
    }

    /// One codepoint can contribute several ASCII characters, which is what
    /// makes budget arithmetic interesting.
    #[test]
    fn one_codepoint_can_fold_to_several() {
        assert_eq!(to_ascii("\u{FB01}n"), "fin"); // ﬁ ligature
        assert_eq!(to_ascii("\u{BD}"), "12"); // ½ -> 1 2, the fraction slash dropped
        assert_eq!(to_ascii("\u{FF28}\u{FF45}"), "He"); // fullwidth
    }

    /// The only source of `?` in the output, and the reason it exists: a stray
    /// tab should be visible rather than silently shifting the layout.
    #[test]
    fn only_control_characters_become_question_marks() {
        assert_eq!(to_ascii("a\tb"), "a?b");
        assert_eq!(to_ascii("a\nb"), "a?b");
        assert_eq!(to_ascii("\u{0}\u{1F}\u{7F}"), "???");
        assert!(!to_ascii("中文").contains('?'), "dropped, not replaced");
    }

    #[test]
    fn empty_stays_empty() {
        assert_eq!(to_ascii(""), "");
        assert_eq!(fit("", 19), "");
    }

    #[test]
    fn each_line_gets_its_own_budget() {
        assert_eq!(Line::WithIcon.budget(), 19);
        assert_eq!(Line::FullWidth.budget(), 21);
        assert_eq!(fit(&"A".repeat(40), 19).len(), 19);
        assert_eq!(fit(&"A".repeat(40), 21).len(), 21);
    }

    /// ⚠️ The ordering test. Folding first means an ellipsis costs three
    /// characters of budget; truncating first would keep more of the title and
    /// produce different bytes than Python for the same input.
    #[test]
    fn truncation_happens_after_folding_not_before() {
        // 10 ellipses fold to 30 dots; the budget takes the first 19 of those.
        assert_eq!(fit(&"\u{2026}".repeat(10), 19), ".".repeat(19));
        // Had it truncated first, 19 ellipses would have folded to 57 dots.
        assert_eq!(fit(&"\u{2026}".repeat(10), 19).len(), 19);
        // Accents cost what their base letter costs, not more.
        assert_eq!(fit(&"é".repeat(25), 19), "e".repeat(19));
    }

    /// Dropped characters do not consume budget, so a CJK title truncates to
    /// whatever Latin text it carries rather than to nothing.
    #[test]
    fn dropped_characters_do_not_spend_budget() {
        assert_eq!(fit("東京東京東京 Tokyo Nights", 19), " Tokyo Nights");
    }

    #[test]
    fn a_line_body_is_line_icon_then_text() {
        let body = line_body(Line::WithIcon, "Artist", Icon::Play);
        assert_eq!(body, b"\x00\x01Artist".to_vec());
        let body = line_body(Line::FullWidth, "Title", Icon::None);
        assert_eq!(body, b"\x01\x00Title".to_vec());
    }

    #[test]
    fn a_line_body_never_exceeds_its_budget() {
        let body = line_body(Line::WithIcon, &"x".repeat(50), Icon::Pause);
        assert_eq!(body.len(), 2 + 19);
        let body = line_body(Line::FullWidth, &"x".repeat(50), Icon::Pause);
        assert_eq!(body.len(), 2 + 21);
    }

    #[test]
    fn the_legacy_set_body_carries_line_zeros_budget() {
        let body = set_body(&"x".repeat(50), Icon::Stop);
        assert_eq!(body[0], 3);
        assert_eq!(body.len(), 1 + 19);
    }

    #[test]
    fn playback_is_big_endian() {
        assert_eq!(playback_body(true, 0x0102, 0x0304), [1, 0x01, 0x02, 0x03, 0x04]);
        assert_eq!(playback_body(false, 0, 0), [0, 0, 0, 0, 0]);
        assert_eq!(playback_body(true, 61, 245), [1, 0, 61, 0, 245]);
    }

    /// Saturating, not wrapping: a 20-hour "track" is a broken timeline, and a
    /// stuck bar is a better lie than a plausible wrong one.
    #[test]
    fn playback_saturates_rather_than_wrapping() {
        assert_eq!(playback_body(true, 70_000, 80_000), [1, 0xFF, 0xFF, 0xFF, 0xFF]);
    }

    /// The whole report, end to end, so the framing and the body are checked
    /// together in the shape the firmware actually parses.
    #[test]
    fn a_framed_line_report_matches_the_firmwares_layout() {
        let f = proto::frame(Channel::Text, SET_LINE, &line_body(Line::WithIcon, "Hi", Icon::Play));
        // [report id][SET_VALUE][TEXT][SET_LINE][line][icon][ascii...]
        assert_eq!(&f[..8], &[0x00, 0x07, 0x12, 0x03, 0x00, 0x01, b'H', b'i']);
        assert!(f[8..].iter().all(|&b| b == 0));
    }

    #[test]
    fn a_framed_playback_report_matches_the_firmwares_layout() {
        let f = proto::frame(Channel::Text, PLAYBACK, &playback_body(true, 61, 245));
        assert_eq!(&f[..9], &[0x00, 0x07, 0x12, 0x04, 1, 0, 61, 0, 245]);
    }

    /// The firmware needs `length >= 8` for PLAYBACK and `>= 5` for SET_LINE;
    /// our reports are always 32 bytes, so this is really a check that framing
    /// pads rather than truncates.
    #[test]
    fn every_text_report_is_a_full_report() {
        for f in [
            proto::frame(Channel::Text, CLEAR, &[]),
            proto::frame(Channel::Text, SET, &set_body("x", Icon::None)),
            proto::frame(Channel::Text, SET_LINE, &line_body(Line::FullWidth, "x", Icon::None)),
            proto::frame(Channel::Text, PLAYBACK, &playback_body(false, 0, 0)),
        ] {
            assert_eq!(f.len(), proto::WIRE_LEN);
        }
    }
}
