//! A reader for one JSON object per line, holding its top-level scalars.
//!
//! The MediaRemote helper speaks line-JSON, and every message the keyboard
//! consumes is a **flat** object: `hello`, `now`, `tick`, `command`, `fatal`.
//! The plan's Settled section records the choice to read that by hand rather
//! than add a dependency, on one condition: a corpus **generated by Python's
//! `json`**, the same oracle pattern as `scripts/gen_ascii_fold.py`
//! (`scripts/gen_json_corpus.py` writes `tests/json_corpus.txt`).
//!
//! ⚠️ **Strict JSON, not "whatever the helper happens to send".** Python's
//! `json.loads` accepts `NaN` and `Infinity`; the generator rejects them with
//! `parse_constant`, and so does this. A reader that is lenient where the oracle
//! is strict passes its corpus and fails on the one line that matters.
//!
//! Nested arrays and objects are **parsed and skipped**, not rejected. No
//! current message carries one, but a later protocol version adding a list must
//! not take the whole media feature down on a reader that could not skip it.
//!
//! Two deliberate departures from Python, both forced by Rust's `String`:
//! - A lone UTF-16 surrogate escape (`"\ud800"`) becomes U+FFFD. Python keeps
//!   the lone surrogate in a `str`, which UTF-8 cannot represent. NSString can
//!   hold one, so a title can carry it.
//! - Numbers are `f64`. Python keeps integers exact; the generator stays inside
//!   the range where the two agree.

use std::fmt;

/// A top-level value, as far as the helper protocol cares.
#[derive(Clone, Debug, PartialEq)]
pub enum Value {
    Str(String),
    Num(f64),
    Bool(bool),
    Null,
    /// An array or object, parsed for validity and not kept.
    Nested,
}

/// Where the reader gave up, and why. Byte offset into the line.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Error {
    pub at: usize,
    pub what: &'static str,
}

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{} at byte {}", self.what, self.at)
    }
}

impl std::error::Error for Error {}

/// One parsed object: its members in source order, duplicates kept.
#[derive(Clone, Debug, PartialEq, Default)]
pub struct Object(pub Vec<(String, Value)>);

impl Object {
    /// The value for `key`. The **last** duplicate wins, as in Python.
    pub fn get(&self, key: &str) -> Option<&Value> {
        self.0.iter().rev().find(|(k, _)| k == key).map(|(_, v)| v)
    }

    /// A string member, or `None` when absent, `null`, or not a string.
    pub fn str(&self, key: &str) -> Option<&str> {
        match self.get(key) {
            Some(Value::Str(s)) => Some(s),
            _ => None,
        }
    }

    /// A number member, or `None` when absent or not a number.
    pub fn num(&self, key: &str) -> Option<f64> {
        match self.get(key) {
            Some(Value::Num(n)) => Some(*n),
            _ => None,
        }
    }

    /// A boolean that may have arrived as a number.
    ///
    /// Objective-C boxes a bare C expression as a number, so `0`/`1` turn up
    /// where `false`/`true` were meant. The helper casts to `BOOL` now, and the
    /// sibling's reader tolerates both anyway (`LenientBooleanConverter`); one
    /// careless `@(...)` should not take the feature down here either.
    pub fn flag(&self, key: &str) -> Option<bool> {
        match self.get(key) {
            Some(Value::Bool(b)) => Some(*b),
            Some(Value::Num(n)) => Some(*n != 0.0),
            _ => None,
        }
    }
}

/// Parse exactly one JSON object, with optional surrounding whitespace.
pub fn parse_object(line: &str) -> Result<Object, Error> {
    let mut p = Parser {
        s: line.as_bytes(),
        i: 0,
        depth: 0,
    };
    p.ws();
    if p.peek() != Some(b'{') {
        return Err(p.err("expected an object"));
    }
    let mut out = Object::default();
    p.i += 1;
    p.ws();
    if p.peek() == Some(b'}') {
        p.i += 1;
    } else {
        loop {
            p.ws();
            if p.peek() != Some(b'"') {
                return Err(p.err("expected a string key"));
            }
            let key = p.string()?;
            p.ws();
            if p.peek() != Some(b':') {
                return Err(p.err("expected ':'"));
            }
            p.i += 1;
            p.ws();
            let value = p.value()?;
            out.0.push((key, value));
            p.ws();
            match p.peek() {
                Some(b',') => p.i += 1,
                Some(b'}') => {
                    p.i += 1;
                    break;
                }
                _ => return Err(p.err("expected ',' or '}'")),
            }
        }
    }
    p.ws();
    if p.i != p.s.len() {
        return Err(p.err("trailing characters"));
    }
    Ok(out)
}

/// Nesting deeper than this is refused rather than recursed into. Python's
/// limit is the interpreter's recursion limit; nothing the helper sends comes
/// within an order of magnitude of either.
const MAX_DEPTH: usize = 64;

struct Parser<'a> {
    s: &'a [u8],
    i: usize,
    depth: usize,
}

impl Parser<'_> {
    fn err(&self, what: &'static str) -> Error {
        Error { at: self.i, what }
    }

    fn peek(&self) -> Option<u8> {
        self.s.get(self.i).copied()
    }

    /// JSON whitespace is exactly these four; Python's decoder agrees.
    fn ws(&mut self) {
        while matches!(self.peek(), Some(b' ' | b'\t' | b'\n' | b'\r')) {
            self.i += 1;
        }
    }

    fn literal(&mut self, word: &'static [u8], value: Value) -> Result<Value, Error> {
        if self.s[self.i..].starts_with(word) {
            self.i += word.len();
            Ok(value)
        } else {
            Err(self.err("invalid literal"))
        }
    }

    fn value(&mut self) -> Result<Value, Error> {
        match self.peek() {
            Some(b'"') => self.string().map(Value::Str),
            Some(b't') => self.literal(b"true", Value::Bool(true)),
            Some(b'f') => self.literal(b"false", Value::Bool(false)),
            Some(b'n') => self.literal(b"null", Value::Null),
            Some(b'-' | b'0'..=b'9') => self.number().map(Value::Num),
            Some(b'[' | b'{') => self.skip_nested().map(|()| Value::Nested),
            _ => Err(self.err("expected a value")),
        }
    }

    fn number(&mut self) -> Result<f64, Error> {
        let start = self.i;
        if self.peek() == Some(b'-') {
            self.i += 1;
        }
        match self.peek() {
            Some(b'0') => self.i += 1, // no leading zeros: "01" stops after the 0
            Some(b'1'..=b'9') => self.digits(),
            _ => return Err(self.err("expected a digit")),
        }
        if self.peek() == Some(b'.') {
            self.i += 1;
            if !matches!(self.peek(), Some(b'0'..=b'9')) {
                return Err(self.err("expected a fraction digit"));
            }
            self.digits();
        }
        if matches!(self.peek(), Some(b'e' | b'E')) {
            self.i += 1;
            if matches!(self.peek(), Some(b'+' | b'-')) {
                self.i += 1;
            }
            if !matches!(self.peek(), Some(b'0'..=b'9')) {
                return Err(self.err("expected an exponent digit"));
            }
            self.digits();
        }
        // The grammar above is JSON's; Rust's float parser is correctly
        // rounded, as is Python's, so the two agree on every digit string.
        let text = std::str::from_utf8(&self.s[start..self.i]).expect("ASCII by construction");
        let value = text.parse::<f64>().map_err(|_| Error {
            at: start,
            what: "unparseable number",
        })?;
        // Python reads an integer spelling as an `int`, and `int` has no
        // negative zero: `-0` is 0, while `-0.0` stays -0.0. The corpus found it.
        let integer = !text.contains(['.', 'e', 'E']);
        Ok(if integer && value == 0.0 { 0.0 } else { value })
    }

    fn digits(&mut self) {
        while matches!(self.peek(), Some(b'0'..=b'9')) {
            self.i += 1;
        }
    }

    fn hex4(&mut self) -> Result<u16, Error> {
        let Some(chunk) = self.s.get(self.i..self.i + 4) else {
            return Err(self.err("truncated \\u escape"));
        };
        let mut v: u16 = 0;
        for &b in chunk {
            let d = match b {
                b'0'..=b'9' => b - b'0',
                b'a'..=b'f' => b - b'a' + 10,
                b'A'..=b'F' => b - b'A' + 10,
                _ => return Err(self.err("bad hex digit in \\u escape")),
            };
            v = v << 4 | u16::from(d);
        }
        self.i += 4;
        Ok(v)
    }

    fn string(&mut self) -> Result<String, Error> {
        debug_assert_eq!(self.peek(), Some(b'"'));
        self.i += 1;
        let mut out = String::new();
        loop {
            // Copy the longest run with nothing special in it in one go. The
            // input is a &str, so any run of bytes that stops before a quote,
            // a backslash or a control character is valid UTF-8 on its own.
            let run = self.i;
            while matches!(self.peek(), Some(b) if b != b'"' && b != b'\\' && b >= 0x20) {
                self.i += 1;
            }
            out.push_str(
                std::str::from_utf8(&self.s[run..self.i])
                    .expect("slice of a &str on char boundaries"),
            );
            match self.peek() {
                None => return Err(self.err("unterminated string")),
                Some(b'"') => {
                    self.i += 1;
                    return Ok(out);
                }
                Some(b'\\') => {
                    self.i += 1;
                    let Some(e) = self.peek() else {
                        return Err(self.err("unterminated escape"));
                    };
                    self.i += 1;
                    match e {
                        b'"' => out.push('"'),
                        b'\\' => out.push('\\'),
                        b'/' => out.push('/'), // NSJSONSerialization writes "\/"
                        b'b' => out.push('\u{08}'),
                        b'f' => out.push('\u{0C}'),
                        b'n' => out.push('\n'),
                        b'r' => out.push('\r'),
                        b't' => out.push('\t'),
                        b'u' => {
                            let hi = self.hex4()?;
                            out.push(self.utf16(hi)?);
                        }
                        _ => {
                            self.i -= 1;
                            return Err(self.err("invalid escape"));
                        }
                    }
                }
                Some(_) => return Err(self.err("control character in string")),
            }
        }
    }

    /// One `\uXXXX` escape, pairing a high surrogate with a following low one.
    /// Anything unpaired becomes U+FFFD (see the module note).
    fn utf16(&mut self, hi: u16) -> Result<char, Error> {
        if (0xD800..0xDC00).contains(&hi) && self.s[self.i..].starts_with(b"\\u") {
            let save = self.i;
            self.i += 2;
            let lo = self.hex4()?;
            if (0xDC00..0xE000).contains(&lo) {
                let c = 0x10000 + ((u32::from(hi) - 0xD800) << 10) + (u32::from(lo) - 0xDC00);
                return Ok(char::from_u32(c).expect("a valid surrogate pair is a scalar"));
            }
            self.i = save; // not a pair: the second escape is read on its own
        }
        Ok(char::from_u32(u32::from(hi)).unwrap_or('\u{FFFD}'))
    }

    fn skip_nested(&mut self) -> Result<(), Error> {
        self.depth += 1;
        if self.depth > MAX_DEPTH {
            return Err(self.err("nesting too deep"));
        }
        let close = if self.peek() == Some(b'[') {
            b']'
        } else {
            b'}'
        };
        let object = close == b'}';
        self.i += 1;
        self.ws();
        if self.peek() == Some(close) {
            self.i += 1;
            self.depth -= 1;
            return Ok(());
        }
        loop {
            self.ws();
            if object {
                if self.peek() != Some(b'"') {
                    return Err(self.err("expected a string key"));
                }
                self.string()?;
                self.ws();
                if self.peek() != Some(b':') {
                    return Err(self.err("expected ':'"));
                }
                self.i += 1;
                self.ws();
            }
            self.value()?;
            self.ws();
            match self.peek() {
                Some(b',') => self.i += 1,
                Some(c) if c == close => {
                    self.i += 1;
                    self.depth -= 1;
                    return Ok(());
                }
                _ => return Err(self.err("expected ',' or a closing bracket")),
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Captured from the sibling's dylib under perl on macOS 27.0, 2026-09-16,
    /// with a YouTube video playing in Chrome. Key order is the helper's.
    const CAPTURED_NOW: &str = r#"{"album":"","stale":false,"elapsedAt":1789586100.2487299,"bundle":"com.google.Chrome","type":"now","title":"iPhone 18 Pro: A Photographer's Review","elapsed":0,"duration":948.14099999999996,"rate":1,"artist":"Tyler Stalman","artwork":"3d89751c57ab860a5adb8374cf27ebeae7752bb9","playing":true}"#;

    #[test]
    fn a_captured_now_line_reads_whole() {
        let o = parse_object(CAPTURED_NOW).unwrap();
        assert_eq!(o.str("type"), Some("now"));
        assert_eq!(o.str("bundle"), Some("com.google.Chrome"));
        assert_eq!(
            o.str("title"),
            Some("iPhone 18 Pro: A Photographer's Review")
        );
        assert_eq!(o.str("artist"), Some("Tyler Stalman"));
        assert_eq!(o.flag("playing"), Some(true));
        assert_eq!(o.flag("stale"), Some(false));
        assert_eq!(o.num("duration"), Some(948.141));
        assert_eq!(o.num("elapsedAt"), Some(1789586100.2487299));
        assert_eq!(o.num("rate"), Some(1.0));
    }

    /// Nothing playing, byte for byte what the helper sent the same day.
    #[test]
    fn the_idle_line_has_a_null_bundle() {
        let o =
            parse_object(r#"{"playing":false,"bundle":null,"type":"now","stale":false}"#).unwrap();
        assert_eq!(o.get("bundle"), Some(&Value::Null));
        assert_eq!(o.str("bundle"), None);
        assert_eq!(o.flag("playing"), Some(false));
    }

    #[test]
    fn ns_json_escapes_slashes_and_unicode_survives() {
        let o =
            parse_object(r#"{"title":"AC\/DC \u2014 Back in Black","artist":"Beyonc\u00e9 🎵"}"#)
                .unwrap();
        assert_eq!(o.str("title"), Some("AC/DC — Back in Black"));
        assert_eq!(o.str("artist"), Some("Beyoncé 🎵"));
    }

    #[test]
    fn surrogate_pairs_join_and_lone_ones_become_replacement() {
        let o =
            parse_object(r#"{"a":"\ud83c\udfb5","b":"x\ud800y","c":"\udc00","d":"\ud800\u0041"}"#)
                .unwrap();
        assert_eq!(o.str("a"), Some("🎵"));
        assert_eq!(o.str("b"), Some("x\u{FFFD}y"));
        assert_eq!(o.str("c"), Some("\u{FFFD}"));
        assert_eq!(o.str("d"), Some("\u{FFFD}A"));
    }

    #[test]
    fn booleans_may_arrive_as_numbers() {
        let o = parse_object(r#"{"stale":0,"playing":1}"#).unwrap();
        assert_eq!(o.flag("stale"), Some(false));
        assert_eq!(o.flag("playing"), Some(true));
    }

    #[test]
    fn nested_values_are_skipped_not_fatal() {
        let o = parse_object(
            r#"{"type":"now","queue":[1,{"a":[true,null]},"x"],"meta":{},"title":"T"}"#,
        )
        .unwrap();
        assert_eq!(o.get("queue"), Some(&Value::Nested));
        assert_eq!(o.str("title"), Some("T"));
    }

    #[test]
    fn the_last_duplicate_wins() {
        let o = parse_object(r#"{"title":"old","title":"new"}"#).unwrap();
        assert_eq!(o.str("title"), Some("new"));
    }

    #[test]
    fn strictness_matches_the_oracle() {
        for bad in [
            "",
            "[]",
            "{",
            "{\"a\"}",
            "{\"a\":}",
            "{\"a\":1,}",
            "{'a':1}",
            "{\"a\":01}",
            "{\"a\":1.}",
            "{\"a\":.5}",
            "{\"a\":NaN}",
            "{\"a\":Infinity}",
            "{\"a\":-}",
            "{\"a\":\"\t\"}",
            "{\"a\":\"\\x\"}",
            "{\"a\":\"\\u12\"}",
            "{\"a\":tru}",
            "{\"a\":1} x",
            "{\"a\":[1,]}",
            "{\"a\":1e}",
        ] {
            assert!(parse_object(bad).is_err(), "should reject {bad:?}");
        }
        assert!(parse_object(" \t{ \"a\" : -0.5e+3 }\r\n").is_ok());
    }

    #[test]
    fn absurd_nesting_is_refused_not_recursed() {
        let deep = format!("{{\"a\":{}{}}}", "[".repeat(100_000), "]".repeat(100_000));
        assert_eq!(parse_object(&deep).unwrap_err().what, "nesting too deep");
    }
}
