#!/usr/bin/env python3
"""Generate ak820-agent's ASCII fold table from Python's own unicodedata.

The Rust agent has to reproduce `hostagent/ak820text.py`'s `to_ascii()` exactly,
because that function decides what reaches the LCD and the port must not quietly
change what a track title looks like. Python gets NFKD from the standard
library; Rust's std has no normalization at all.

Rather than add a dependency for it -- the crate deliberately has exactly one,
and `unicode-normalization` would bring ~100 KB of tables to serve a path that
throws away every non-ASCII character immediately after decomposing -- the table
is generated HERE, from the same library the oracle uses, and checked in.

⚠️ Generated, not authored. Do not edit the output by hand; edit this and re-run:

    python scripts/gen_ascii_fold.py

## What is being reproduced

    def to_ascii(s):
        for k, v in SUBS.items():
            s = s.replace(k, v)
        s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode()
        return "".join(c if 0x20 <= ord(c) < 0x7F else "?" for c in s)

Three steps, and each is handled somewhere specific:

1. `SUBS` -- a punctuation transliteration applied BEFORE normalization. It is
   not redundant: U+2018/2019/201C/201D and U+2013/2014 have no compatibility
   decomposition at all, so without this they would simply vanish. Baked into
   the table below as overrides.
2. NFKD, then drop everything non-ASCII. This is the table.
3. Control characters become `?`. Handled in Rust, not here: NFKD never emits a
   C0 control and no `SUBS` value contains one, so a control in the output can
   only have come from a control in the input.

## Why a per-codepoint table is equivalent to normalizing the whole string

NFKD is compatibility decomposition followed by canonical ordering. Ordering
only permutes combining marks, which are all >= U+0300 and therefore dropped by
the ASCII filter anyway -- so it cannot change which characters survive. Every
`SUBS` key is a single character, so replacement is per-character too. The
differential test in `src/text/mod.rs` checks this against real Python output
rather than trusting the argument.
"""
import sys
import unicodedata
from pathlib import Path

# Must stay identical to SUBS in hostagent/ak820text.py.
SUBS = {
    "‘": "'",
    "’": "'",
    "“": '"',
    "”": '"',
    "–": "-",
    "—": "-",
    "…": "...",
    " ": " ",
}

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "ak820-agent" / "src" / "text" / "fold_table.rs"
PARITY = ROOT / "ak820-agent" / "tests" / "ascii_fold_parity.rs"


def real_to_ascii():
    """The actual `to_ascii` from hostagent/ak820text.py, not a copy of it.

    Importing it needs two stubs: the module pulls in `venv_bootstrap` (which
    would re-exec us under a different interpreter) and `hid` (which would drag
    in hidapi for a function that touches no device). Neither is used by
    `to_ascii`, and stubbing them is what lets the parity fixture be generated
    from the **oracle itself** rather than from a second implementation that
    could drift from it in exactly the way the fixture exists to detect.
    """
    import types

    for name in ("venv_bootstrap", "hid"):
        if name not in sys.modules:
            stub = types.ModuleType(name)
            stub.ensure = lambda *a, **k: None
            sys.modules[name] = stub
    sys.path.insert(0, str(ROOT / "hostagent"))
    import ak820text

    return ak820text.to_ascii, ak820text.SUBS, ak820text.MAXLEN


def fold(cp: int) -> str:
    """The ASCII a single non-ASCII codepoint contributes, possibly empty."""
    ch = chr(cp)
    if ch in SUBS:
        return SUBS[ch]
    return "".join(c for c in unicodedata.normalize("NFKD", ch) if ord(c) < 0x80)


def main() -> int:
    entries = []
    for cp in range(0x80, 0x110000):
        # Surrogates are not scalar values; Rust `char` cannot hold one, so a
        # Rust input can never contain one and an entry would be unreachable.
        if 0xD800 <= cp <= 0xDFFF:
            continue
        folded = fold(cp)
        if folded:
            entries.append((cp, folded))

    blob = "".join(text for _, text in entries)
    offsets, at = [], 0
    for _, text in entries:
        offsets.append(at)
        at += len(text)
    offsets.append(at)

    assert all(0x20 <= ord(c) < 0x7F for c in blob), "a fold produced a control char"
    assert at == len(blob) and at < 0xFFFF, "blob does not fit a u16 offset"

    lines = [
        "//! ASCII fold table -- GENERATED by scripts/gen_ascii_fold.py. Do not edit.",
        "//!",
        "//! Every codepoint whose NFKD decomposition contributes at least one ASCII",
        "//! character, plus `ak820text.py`'s SUBS punctuation overrides. Codepoints",
        "//! absent from KEYS fold to nothing, exactly as `.encode(\"ascii\", \"ignore\")`",
        "//! drops them.",
        "//!",
        f"//! Unicode {unicodedata.unidata_version}, via CPython {sys.version.split()[0]}.",
        f"//! {len(entries)} codepoints, {len(blob)} bytes of replacement text.",
        "",
        "/// Sorted, so lookup is a binary search.",
        f"pub const KEYS: [u32; {len(entries)}] = [",
    ]
    for i in range(0, len(entries), 12):
        lines.append("    " + " ".join(f"0x{cp:X}," for cp, _ in entries[i : i + 12]))
    lines += [
        "];",
        "",
        "/// `KEYS[i]` folds to `BLOB[OFFSETS[i]..OFFSETS[i + 1]]`.",
        f"pub const OFFSETS: [u16; {len(offsets)}] = [",
    ]
    for i in range(0, len(offsets), 16):
        lines.append("    " + " ".join(f"{o}," for o in offsets[i : i + 16]))
    lines += [
        "];",
        "",
        "/// Every replacement, concatenated. ASCII by construction.",
        "pub const BLOB: &str = concat!(",
    ]
    for i in range(0, len(blob), 64):
        chunk = blob[i : i + 64].replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    "{chunk}",')
    lines += ["];".replace("];", ");"), ""]

    # ⚠️ Python's str.strip() uses str.isspace(), which is NOT the same set as
    # Rust's char::is_whitespace(). Python additionally treats the C0
    # separators U+001C..U+001F as space; Rust does not, because they lack the
    # Unicode White_Space property.
    #
    # That difference is not cosmetic here. An artist field of "\x1c" is empty
    # to Python and one character to Rust -- and `Snapshot::lines` puts the
    # title on the NARROW row when the artist is empty and the wide row when it
    # is not. So a stray separator would move the title to a different row and
    # change its budget. Generated for the same reason the fold table is.
    spaces = [
        cp
        for cp in range(0x110000)
        if not (0xD800 <= cp <= 0xDFFF) and chr(cp).isspace()
    ]
    lines += [
        f"/// Every codepoint Python's `str.isspace()` accepts. {len(spaces)} of them.",
        "///",
        "/// Rust's `char::is_whitespace` is *nearly* this set but omits",
        "/// U+001C..U+001F, which Python strips and we therefore must too.",
        f"pub const PY_SPACE: [char; {len(spaces)}] = [",
    ]
    for i in range(0, len(spaces), 8):
        lines.append(
            "    " + " ".join(f"'\\u{{{cp:X}}}'," for cp in spaces[i : i + 8])
        )
    lines += ["];", ""]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"{OUT}: {len(entries)} codepoints, {len(blob)} bytes of text")

    write_parity(entries)
    return 0


def rust_str(s: str) -> str:
    """A Rust string literal for arbitrary text, escaped so it survives review."""
    out = ['"']
    for c in s:
        if c == "\\":
            out.append("\\\\")
        elif c == '"':
            out.append('\\"')
        elif 0x20 <= ord(c) < 0x7F:
            out.append(c)
        else:
            out.append(f"\\u{{{ord(c):X}}}")
    out.append('"')
    return "".join(out)


def write_parity(entries):
    """Emit a test that checks the Rust fold against the real Python function.

    ⚠️ The expected values come from `hostagent/ak820text.py`'s own `to_ascii`,
    imported and called -- not from `fold()` above. That is the whole point: if
    the per-codepoint table were built on a wrong understanding of NFKD, or the
    SUBS overrides were applied in the wrong order, both `fold()` and the Rust
    code would be wrong together and agree with each other. Only the oracle can
    catch that.
    """
    to_ascii, subs, maxlen = real_to_ascii()

    cases = []
    # Every codepoint the table knows about, one at a time. This is the
    # exhaustive half: it proves the table is right entry by entry.
    for cp, _ in entries:
        cases.append(chr(cp))
    # And a codepoint from each of the ranges that fold to NOTHING, which the
    # table cannot get wrong by having a bad entry -- only by having one it
    # should not.
    cases += ["\u4e2d\u6587", "\u0416", "\u03b1\u03b2", "\U0001F3B5", "\u3042"]
    # Strings, because folding is per-character but the contract is per-string:
    # multi-character folds, combining marks, and the SUBS punctuation in situ.
    cases += [
        "",
        "Beyonc\u00e9",
        "Sigur R\u00f3s",
        "Mot\u00f6rhead",
        "Bj\u00f6rk \u2013 J\u00f3ga",
        "\u2018Heroes\u2019",
        "\u201cQuoted\u201d",
        "Don\u2019t Stop \u2026 Believin\u2019",
        "caf\u00e9 \u00bd \ufb01n",
        "e\u0301galit\u0301e",              # already-decomposed combining marks
        "\uff28\uff45\uff4c\uff4c\uff4f",   # fullwidth
        "tab\there",
        "nl\nhere",
        "\x00\x1f\x7f",
        "A" * 40,
        "\u00e9" * 40,
        "\u2026" * 10,
    ]

    lines = [
        "//! ASCII fold parity -- GENERATED by scripts/gen_ascii_fold.py. Do not edit.",
        "//!",
        "//! Expected values produced by calling `to_ascii` in",
        "//! `hostagent/ak820text.py` directly, so this compares the Rust port to the",
        "//! **oracle**, not to a second copy of the same assumptions.",
        "//!",
        f"//! Unicode {unicodedata.unidata_version}, CPython {sys.version.split()[0]}.",
        "",
        "use ak820_agent::text;",
        "",
        f"/// `(input, what Python's to_ascii returns)`. {len(cases)} cases.",
        f"const CASES: [(&str, &str); {len(cases)}] = [",
    ]
    for case in cases:
        lines.append(f"    ({rust_str(case)}, {rust_str(to_ascii(case))}),")
    lines += [
        "];",
        "",
        "#[test]",
        "fn rust_folding_matches_python() {",
        "    let mut wrong = Vec::new();",
        "    for (input, expected) in CASES {",
        "        let got = text::to_ascii(input);",
        "        if got != expected {",
        "            wrong.push(format!(\"{input:?}: python {expected:?}, rust {got:?}\"));",
        "        }",
        "    }",
        "    assert!(wrong.is_empty(), \"{} of {} cases differ:\\n{}\",",
        "        wrong.len(), CASES.len(), wrong.join(\"\\n\"));",
        "}",
        "",
        "/// The budgets are part of the same contract and just as easy to get wrong.",
        "#[test]",
        "fn line_budgets_match_python() {",
        f"    assert_eq!(text::MAX_LEN, [{maxlen[0]}, {maxlen[1]}]);",
        "}",
        "",
        f"/// {len(subs)} punctuation overrides applied before normalization.",
        "#[test]",
        "fn subs_punctuation_survives_folding() {",
    ]
    for k, v in subs.items():
        lines.append(f"    assert_eq!(text::to_ascii({rust_str(k)}), {rust_str(v)});")
    lines += ["}", ""]

    PARITY.parent.mkdir(parents=True, exist_ok=True)
    PARITY.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"{PARITY}: {len(cases)} parity cases")


if __name__ == "__main__":
    raise SystemExit(main())
