#!/usr/bin/env python3
"""Generate the JSON reader's parity corpus, with Python's `json` as the oracle.

    python3 scripts/gen_json_corpus.py ak820-agent/spikes/s1-mediaremote/tests/json_corpus.txt

The macOS agent reads the MediaRemote helper's line-JSON with a hand-rolled
flat-object reader instead of a dependency. The cross-platform plan accepts
that on one condition: a corpus generated by Python's `json`, the same pattern
as gen_ascii_fold.py, so the reader is checked against a real decoder rather
than against what its author thought JSON was.

Seeded, so the file is reproducible: regenerate it, and `git diff` shows
nothing unless this script or Python's decoder changed.

One case per line, tab-separated:

    <input as hex>  ERR
    <input as hex>  OK  <key hex>=<T>:<value> ...

T is S (UTF-8 hex), N (float repr), B (0/1), Z (null) or X (nested, skipped).

Two mappings keep the oracle honest about what Rust can hold, and each matches a
documented departure in the reader:
- a lone surrogate in a Python str becomes U+FFFD, since Rust strings are UTF-8
- a number is compared as float(value); integers stay inside +-1e300, where
  float() cannot overflow
And one strictness the default decoder lacks: NaN/Infinity are rejected, as
JSON says, via parse_constant.
"""
import json
import random
import sys

SEED = 20260916
rng = random.Random(SEED)


def reject_constant(name):
    raise ValueError(f"non-JSON constant {name}")


def oracle(text):
    """The expected outcome for `text`, or None when Python refuses it."""
    try:
        value = json.loads(text, parse_constant=reject_constant)
    except (ValueError, RecursionError):
        return None
    if not isinstance(value, dict):
        return None                      # the reader takes exactly one object
    return value


def utf8_hex(s):
    # Lone surrogates -> U+FFFD, per UTF-16 code unit, as the reader does.
    fixed = s.encode("utf-16-le", "surrogatepass").decode("utf-16-le", "replace")
    return fixed.encode("utf-8").hex()


def encode_expect(obj, text):
    # Python's dict keeps the LAST duplicate, and the reader's get() does too,
    # but the reader also keeps every member in order. Compare what get() sees:
    # the distinct keys in order of last appearance is not recoverable from a
    # dict, so emit the dict's view and let the test look each key up.
    parts = []
    for k, v in obj.items():
        if isinstance(v, bool):
            t = f"B:{int(v)}"
        elif v is None:
            t = "Z:"
        elif isinstance(v, (int, float)):
            t = f"N:{float(v)!r}"
        elif isinstance(v, str):
            t = f"S:{utf8_hex(v)}"
        else:
            t = "X:"
        parts.append(f"{utf8_hex(k)}={t}")
    return "OK\t" + "\t".join(parts)


ALPHABET = (
    list("abcdefghijklmnopqrstuvwxyz ABCXYZ0123456789-_:,.'!?()[]{}\"\\/")
    + ["\t", "\n", "\r", "\b", "\f", "\x00", "\x1f", "\x7f", "\u0080", "\u00e9", "\u2014",
       "\u200b", "\ufeff", "\uffff", "\U0001f3b5", "\U0010ffff", "\ud800", "\udfff", "\u00a0"]
)


def rand_string(max_len=12):
    return "".join(rng.choice(ALPHABET) for _ in range(rng.randint(0, max_len)))


def rand_number():
    kind = rng.randrange(7)
    if kind == 0:
        return rng.randint(-10**6, 10**6)
    if kind == 1:
        return rng.randint(-10**300, 10**300)
    if kind == 2:
        return rng.uniform(-1e6, 1e6)
    if kind == 3:
        return rng.choice([0.0, -0.0, 5e-324, 1.7976931348623157e308, 2.2250738585072014e-308, 0.1, 1e21, 1e-7])
    if kind == 4:
        return rng.random() * 10 ** rng.randint(-300, 300)
    if kind == 5:
        return 1789586100.2487299 + rng.random()   # an elapsedAt
    return rng.choice([948.14099999999996, 0, 1, -1])


def rand_scalar(depth=0):
    kind = rng.randrange(9 if depth < 3 else 6)
    if kind < 2:
        return rand_string()
    if kind < 4:
        return rand_number()
    if kind == 4:
        return rng.choice([True, False])
    if kind == 5:
        return None
    if kind in (6, 7):
        return [rand_scalar(depth + 1) for _ in range(rng.randint(0, 3))]
    return {rand_string(4): rand_scalar(depth + 1) for _ in range(rng.randint(0, 3))}


def rand_object():
    return {rand_string(8): rand_scalar() for _ in range(rng.randint(0, 8))}


def serialize(obj):
    """Several spellings of one object, including NSJSONSerialization's."""
    variants = [
        json.dumps(obj),
        json.dumps(obj, ensure_ascii=False),
        json.dumps(obj, separators=(",", ":")),
        json.dumps(obj, ensure_ascii=False, separators=(",", ":")).replace("/", "\\/"),
    ]
    return rng.choice(variants)


MUTATIONS = [",", ":", "\"", "\\", "}", "{", "]", "[", " ", "\t", "\n", "0", "-", "e", ".", "t", "n",
             "\\u", "\\ud800", "\\udc00", "NaN", "Infinity", "01", "\x01", "'"]


def mutate(text):
    op = rng.randrange(4)
    if not text:
        return rng.choice(MUTATIONS)
    i = rng.randrange(len(text) + 1)
    if op == 0:
        return text[:i] + rng.choice(MUTATIONS) + text[i:]
    if op == 1:
        return text[:i] + text[i + 1:]
    if op == 2:
        return text[:i]
    return text[:i] + rng.choice(MUTATIONS) + text[i + 1:]


HAND = [
    # Captured from the helper on macOS 27.0, 2026-09-16.
    '{"album":"","stale":false,"elapsedAt":1789586100.2487299,"bundle":"com.google.Chrome","type":"now","title":"iPhone 18 Pro: A Photographer\'s Review","elapsed":0,"duration":948.14099999999996,"rate":1,"artist":"Tyler Stalman","artwork":"3d89751c57ab860a5adb8374cf27ebeae7752bb9","playing":true}',
    '{"playing":false,"bundle":null,"type":"now","stale":false}',
    '{"type":"hello","pid":21842}',
    '{"type":"tick","seq":7}',
    '{"type":"fatal","error":"MediaRemote stopped answering; restarting"}',
    '{"type":"command","name":"toggle","accepted":true}',
    '{"title":"AC\\/DC","a":"\\ud83c\\udfb5","b":"\\ud800\\ud800\\udc00","c":"\\udc00\\ud800"}',
    '{"a":1,"a":2}', '{}', ' {"a" : [ ] , "b" : { } } ', '{"a":-0}', '{"a":1E+2}', '{"a":1e-2}',
    '{"a":NaN}', '{"a":-Infinity}', '{"a":1,}', '{,}', '{"a" 1}', '[{"a":1}]', '"x"', '',
    '{"a":"\\u00"}', '{"a":"\\uZZZZ"}', '{"a":"\x1f"}', '{"a":"\x7f"}', '{"a":tRue}', '{"a":nul}',
    '{"a":' + "[" * 60 + "]" * 60 + '}',
]


def main():
    out_path = sys.argv[1]
    lines = []
    seen = set()

    def add(text):
        if text in seen:
            return
        seen.add(text)
        value = oracle(text)
        expect = "ERR" if value is None else encode_expect(value, text)
        try:
            raw = text.encode("utf-8")
        except UnicodeEncodeError:
            return                        # a lone surrogate in the INPUT: not a &str, skip
        lines.append(raw.hex() + "\t" + expect)

    for text in HAND:
        add(text)
    for _ in range(3500):
        add(serialize(rand_object()))
    for _ in range(3500):
        base = serialize(rand_object())
        for _ in range(rng.randint(1, 3)):
            base = mutate(base)
        add(base)

    with open(out_path, "w", encoding="ascii", newline="\n") as f:
        f.write(f"# generated by scripts/gen_json_corpus.py (seed {SEED}, Python {sys.version.split()[0]}); do not edit\n")
        f.write("\n".join(lines) + "\n")
    ok = sum(1 for l in lines if "\tOK" in l)
    print(f"{len(lines)} cases ({ok} accepted, {len(lines) - ok} rejected) -> {out_path}")


if __name__ == "__main__":
    main()
