//! The flat JSON reader against Python's `json`, case by case.
//!
//! `tests/json_corpus.txt` is generated by `scripts/gen_json_corpus.py`; never
//! edit it by hand. Every accepted case must read to exactly the members Python
//! produced, and every case Python refused must be refused here too.

use s1::json::{parse_object, Value};

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn unhex_str(s: &str) -> String {
    String::from_utf8(unhex(s)).expect("the generator writes UTF-8")
}

#[test]
fn every_case_agrees_with_python() {
    let corpus = include_str!("json_corpus.txt");
    let mut checked = 0;
    let mut failures = Vec::new();
    for (n, line) in corpus.lines().enumerate() {
        if line.starts_with('#') || line.is_empty() {
            continue;
        }
        let mut fields = line.split('\t');
        let input = unhex_str(fields.next().unwrap());
        let verdict = fields.next().unwrap();
        let got = parse_object(&input);
        checked += 1;
        match (verdict, got) {
            ("ERR", Ok(obj)) => {
                failures.push(format!("line {}: accepted {input:?} as {obj:?}", n + 1))
            }
            ("ERR", Err(_)) => {}
            ("OK", Err(e)) => failures.push(format!("line {}: refused {input:?}: {e}", n + 1)),
            ("OK", Ok(obj)) => {
                let expected: Vec<(String, &str)> = fields
                    .filter(|f| !f.is_empty())
                    .map(|f| {
                        let (k, v) = f.split_once('=').unwrap();
                        (unhex_str(k), v)
                    })
                    .collect();
                // Python's dict: distinct keys, last value wins. Compare what
                // `get` returns for each, and that no key is missing or extra.
                let mut keys: Vec<&str> = obj.0.iter().map(|(k, _)| k.as_str()).collect();
                keys.sort_unstable();
                keys.dedup();
                if keys.len() != expected.len() {
                    failures.push(format!(
                        "line {}: {} distinct keys, Python had {}",
                        n + 1,
                        keys.len(),
                        expected.len()
                    ));
                    continue;
                }
                for (key, spec) in &expected {
                    let (t, raw) = spec.split_at(2);
                    let ok = match (t, obj.get(key)) {
                        ("S:", Some(Value::Str(s))) => *s == unhex_str(raw),
                        ("N:", Some(Value::Num(x))) => {
                            let want: f64 = raw.parse().unwrap();
                            x.to_bits() == want.to_bits()
                        }
                        ("B:", Some(Value::Bool(b))) => (*b as u8).to_string() == raw,
                        ("Z:", Some(Value::Null)) => true,
                        ("X:", Some(Value::Nested)) => true,
                        _ => false,
                    };
                    if !ok {
                        failures.push(format!(
                            "line {}: key {key:?} = {:?}, Python {spec}",
                            n + 1,
                            obj.get(key)
                        ));
                    }
                }
            }
            (other, _) => panic!("line {}: bad verdict {other:?}", n + 1),
        }
    }
    assert!(checked > 4000, "corpus too small: {checked}");
    assert!(
        failures.is_empty(),
        "{} of {checked} disagree:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
